In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('fakenewssites.csv')

In [4]:
df1.head(10)

                    Site name   Type of site          Registration
0                  16WMPO.com  Imposter site  Scottsdale, Ariz. **
1               24online.news  Imposter site        Panama, Pa. **
2                   24wpn.com      Fake news      Veles, Macedonia
3              24x365live.com      Fake news   Kobenhavn, Denmark
4            247NewsMedia.com      Fake news   Kumanovo, Macedonia
5                a-news24.com      Fake news    Dhaka, Bangladesh
6              ABCNews.com.co  Imposter site        Phoenix, Ariz.
7  actualidadpanamericana.com    Parody site  Scottsdale, Ariz. **
8         AlabamaObserver.com  Imposter site   Toronto, Canada !!!
9         AmericanFlavor.news      Fake news         Panama, Pa. *

In [5]:
filter1 = df1["Type of site"]=="Fake news"
df1.where(filter1 ,inplace=True)
df1 = df1.dropna(how='any',axis=0)

In [21]:
df1 = df1.reset_index()

In [22]:
df1

     index             Site name Type of site         Registration
0        2             24wpn.com    Fake news     Veles, Macedonia
1        3        24x365live.com    Fake news  Kobenhavn, Denmark
2        4      247NewsMedia.com    Fake news  Kumanovo, Macedonia
3        5          a-news24.com    Fake news   Dhaka, Bangladesh
4        9   AmericanFlavor.news    Fake news        Panama, Pa. *
..     ...                   ...          ...                  ...
186    319   WorldNewsCircle.com    Fake news          Brea, CA !!
187    321  WorldPoliticsNow.com    Fake news     Nassau, Bahamas!
188    322    World.Politics.com    Fake news  Fort Lauderdale, FL
189    323         WorldTruth.tv    Fake news            GoDaddy**
190    326      YourNewsWire.com    Fake news            GoDaddy**

[191 rows x 4 columns]